services:
  - type: web
    name: anita-pinturitas-payment-server-2025
    env: python
    buildCommand: pip install -r requirements.txt --force-reinstall
    startCommand: python server_2025.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 