services:
  - type: web
    name: anita-pinturitas-stripe
    env: python
    buildCommand: pip install -r requirements.txt --force-reinstall
               startCommand: python payment_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 